
##############################################################
#
# This file can be used to compile the executables using any
# standard Fortran 90 compiler (e.g. the Linux INTEL Fortran 95)
# This makefile was written by Remco van den Bosch, using the
# Leiden, 2009
#
##############################################################
FAST=TRUE
#PROFILE=TRUE
ABEL_NO_INTERPOL=true
#FORTRAN=path/to/gfortran
FORTRAN ?= gfortran
compilername=gfortran
#flags=-fno-use-linker-plugin

#PROFILEDIR=~/profile/

BUILDDIR ?= build
BINDIR ?= bin
SRCDIR ?= source
NUMERICSDIR := $(SRCDIR)/numerics
UNUSEDDIR := $(SRCDIR)/unused
OBJDIR := $(BUILDDIR)/obj
MODDIR := $(BUILDDIR)/mod
BUILD_DIRS := $(BINDIR) $(OBJDIR) $(MODDIR)

flags += -Wuninitialized

ifeq ($(compilername),ifort)
ifdef FAST
  #flags = -fast
  flags += -O3 -IPO -xT -prefetch -pad
  flags += -fno-fnalias
else
  flags += -C -g -inline-debug-info
endif



ifdef PROFILEDIR
ifdef PROFILE
flags  += -prof-dir $(PROFILEDIR)
flags  +=  -prof-gen
else
  ifdef FAST
    flags  += -prof-dir $(PROFILEDIR)
    flags  += -prof-use
  endif
endif
endif


fortran90 = $(FORTRAN) $(flags)     -c
fortran77 = $(FORTRAN) $(flags) -W0 -c
link      = $(FORTRAN) $(flags)     -o
endif

ifeq ($(compilername),F)
  fortran90 = F -ieee=stop -C -O4   -c
  fortran77 = g77.old -O2   -c
  link = F -ieee=stop -C -O4   -o
endif

ifeq ($(compilername),g95)
  fortran90 = ~/local/bin/g95 -c -O3 -m64  -c
  fortran77 = ~/local/bin/g95 -c -O3 -m64  -c
  link = ~/local/bin/g95 -o -O3 -m64 -o
endif

ifeq ($(compilername),gfortran)
  ifdef FAST
   flags +=    -ffast-math -O3 -march=native -fomit-frame-pointer -m64
   flags +=    -funroll-loops -ftree-loop-linear
#   flags += -fno-protect-parens
#   flags +=  -fwhole-file #-fwhole-program # -flto
   flags += -std=legacy
  else
   flags +=  -m64 -g  -ggdb -fbounds-check -fcheck-array-temporaries
   #flags = -m64   -g -ffast-math -O3 -march=native -fomit-frame-pointer -m64
  endif

  ifdef PROFILEDIR
  ifdef PROFILE
    flags  += -fprofile-generate=$(PROFILEDIR)
  else
    ifdef FAST
        flags  += -fprofile-use=$(PROFILEDIR)
    endif
  endif
  endif

   # on MAC OS X we can use the built-in BLAS/LAPACK
  #flags += -fexternal-blas -framework Accelerate
  flags += -fexternal-blas

  modflags = -J$(MODDIR) -I$(MODDIR)
  fortran90 = $(FORTRAN) $(flags) $(modflags) -c
  fortran77 = $(FORTRAN) $(flags) $(modflags) -c
  link = $(FORTRAN) $(flags) $(modflags) -o
#  link = gfortran $(flags) -o
endif

##########################################################

PROGRAMS = $(BINDIR)/orbitstart $(BINDIR)/orbitstart_bar $(BINDIR)/orblib_new_mirror $(BINDIR)/orblib_bar $(BINDIR)/triaxmass $(BINDIR)/triaxmass_bar $(BINDIR)/triaxmassbin $(BINDIR)/triaxmassbin_bar

all : $(PROGRAMS)
nogal : all

$(BUILD_DIRS):
	mkdir -p $@

#########################################################
#
# Store a copy of all compiled version in RCS as backup
#
#########################################################

RCS : Makefile $(SRCDIR)/iniparam_f.f90 $(SRCDIR)/orblib_f_new_mirror.f90 $(SRCDIR)/triaxpotent.f90 $(SRCDIR)/interpolpotent.f90 $(SRCDIR)/orblibprogram.f90 $(SRCDIR)/triaxmassbin.f90 $(SRCDIR)/triaxmass.f90 $(SRCDIR)/orbitstart.f90 $(SRCDIR)/dmpotent.f90
	ci -q -l -mcompile Makefile $(SRCDIR)/iniparam_f.f90 $(SRCDIR)/orblib_f_new_mirror.f90 $(SRCDIR)/triaxpotent.f90 $(SRCDIR)/interpolpotent.f90 $(SRCDIR)/orblibprogram.f90 $(SRCDIR)/triaxmassbin.f90 $(SRCDIR)/triaxmass.f90 $(SRCDIR)/orbitstart.f90 $(SRCDIR)/dmpotent.f90

##########################################################
#
# Choice between two integrators
#
# DOP853 is the more accurate and is less prone to fail
# integrating the orbit trajectory, but it is slower too.
#
##########################################################

# DOPRI5 is kept in source/unused as an inactive alternate integrator.
#DOPCDE = $(UNUSEDDIR)/dopri5.f
#DOPOBJ = $(OBJDIR)/dopri5.o

DOPCDE = $(NUMERICSDIR)/dop853.f
DOPOBJ = $(OBJDIR)/dop853.o


######################################################
#
# MGE Code.
#
######################################################

MGECDE = $(SRCDIR)/ran1_nr.f $(NUMERICSDIR)/numeric_kinds_f.f90 $(NUMERICSDIR)/dqxgs.f $(NUMERICSDIR)/ellipint.f90 $(SRCDIR)/iniparam_f.f90 $(SRCDIR)/triaxpotent.f90 $(SRCDIR)/dmpotent.f90 $(SRCDIR)/interpolpotent.f90 $(NUMERICSDIR)/specfunc_beta.f90
MGEOBJ = $(OBJDIR)/ran1_nr.o $(OBJDIR)/numeric_kinds_f.o $(OBJDIR)/dqxgs.o $(OBJDIR)/iniparam_f.o $(OBJDIR)/triaxpotent.o $(OBJDIR)/dmpotent.o $(OBJDIR)/interpolpotent.o $(OBJDIR)/ellipint.o $(OBJDIR)/specfunc_beta.o

$(OBJDIR)/iniparam_f.o: $(SRCDIR)/iniparam_f.f90 $(OBJDIR)/numeric_kinds_f.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/iniparam_f.f90

$(OBJDIR)/triaxpotent.o : $(SRCDIR)/triaxpotent.f90 $(OBJDIR)/ellipint.o $(OBJDIR)/numeric_kinds_f.o $(OBJDIR)/iniparam_f.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/triaxpotent.f90

$(OBJDIR)/triaxmass_f.o : $(SRCDIR)/triaxmass_f.f90 $(OBJDIR)/nag.o $(OBJDIR)/triaxpotent.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/triaxmass_f.f90

$(OBJDIR)/triaxmassbin_f.o : $(SRCDIR)/triaxmassbin_f.f90 $(OBJDIR)/nag.o $(OBJDIR)/triaxpotent.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/triaxmassbin_f.f90

$(OBJDIR)/dmpotent.o : $(SRCDIR)/dmpotent.f90 $(OBJDIR)/triaxpotent.o $(OBJDIR)/numeric_kinds_f.o $(OBJDIR)/iniparam_f.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/dmpotent.f90

$(OBJDIR)/interpolpotent.o : $(SRCDIR)/interpolpotent.f90 $(OBJDIR)/triaxpotent.o $(OBJDIR)/numeric_kinds_f.o $(OBJDIR)/iniparam_f.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/interpolpotent.f90

#####################################################
#
# AUX routines
#
###################################################

$(OBJDIR)/ran1_nr.o : $(SRCDIR)/ran1_nr.f | $(BUILD_DIRS)
	$(fortran77) -o $@ $(SRCDIR)/ran1_nr.f

$(OBJDIR)/numeric_kinds_f.o : $(NUMERICSDIR)/numeric_kinds_f.f90 | $(BUILD_DIRS)
	$(fortran90) -o $@ $(NUMERICSDIR)/numeric_kinds_f.f90

$(OBJDIR)/ellipint.o : $(NUMERICSDIR)/ellipint.f90 $(OBJDIR)/numeric_kinds_f.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(NUMERICSDIR)/ellipint.f90

$(OBJDIR)/numrep.o: $(NUMERICSDIR)/numrep.f90 $(OBJDIR)/numeric_kinds_f.o | $(BUILD_DIRS)
	$(fortran77) -o $@ $(NUMERICSDIR)/numrep.f90

$(OBJDIR)/nag.o : $(NUMERICSDIR)/nag.f | $(BUILD_DIRS)
	$(fortran77) -o $@ $(NUMERICSDIR)/nag.f

$(OBJDIR)/numrec_arloc.o : $(NUMERICSDIR)/numrec_arloc.f | $(BUILD_DIRS)
	$(fortran77) -o $@ $(NUMERICSDIR)/numrec_arloc.f

$(OBJDIR)/dop853.o: $(NUMERICSDIR)/dop853.f | $(BUILD_DIRS)
	$(fortran77) -o $@ $(NUMERICSDIR)/dop853.f

$(OBJDIR)/dopri5.o: $(UNUSEDDIR)/dopri5.f | $(BUILD_DIRS)
	$(fortran77) -o $@ $(UNUSEDDIR)/dopri5.f

$(OBJDIR)/dqxgs.o : $(NUMERICSDIR)/dqxgs.f | $(BUILD_DIRS)
	$(fortran77) -o $@ $(NUMERICSDIR)/dqxgs.f

$(OBJDIR)/specfunc_beta.o : $(NUMERICSDIR)/specfunc_beta.f90 $(OBJDIR)/numeric_kinds_f.o | $(BUILD_DIRS)
	$(fortran90) -o $@ $(NUMERICSDIR)/specfunc_beta.f90

####################################################
#
# triaxmass
#
###################################################

triaxmass: $(BINDIR)/triaxmass

$(BINDIR)/triaxmass: $(MGEOBJ) $(OBJDIR)/nag.o $(OBJDIR)/triaxmass_f.o $(SRCDIR)/triaxmass.f90 | $(BUILD_DIRS)
	$(link) $@ $(MGEOBJ) $(OBJDIR)/triaxmass_f.o $(OBJDIR)/nag.o $(SRCDIR)/triaxmass.f90

triaxmass_bar: $(BINDIR)/triaxmass_bar

$(BINDIR)/triaxmass_bar: $(MGEOBJ) $(OBJDIR)/nag.o $(OBJDIR)/triaxmass_f.o $(SRCDIR)/triaxmass_bar.f90 | $(BUILD_DIRS)
	$(link) $@ $(MGEOBJ) $(OBJDIR)/triaxmass_f.o $(OBJDIR)/nag.o $(SRCDIR)/triaxmass_bar.f90

####################################################
#
# triaxmassbin
#
###################################################

triaxmassbin: $(BINDIR)/triaxmassbin

$(BINDIR)/triaxmassbin: $(MGEOBJ) $(OBJDIR)/triaxmassbin_f.o $(SRCDIR)/triaxmassbin.f90 | $(BUILD_DIRS)
	$(link) $@ $(MGEOBJ) $(OBJDIR)/triaxmassbin_f.o $(SRCDIR)/triaxmassbin.f90

triaxmassbin_bar: $(BINDIR)/triaxmassbin_bar

$(BINDIR)/triaxmassbin_bar: $(MGEOBJ) $(OBJDIR)/triaxmassbin_f.o $(SRCDIR)/triaxmassbin_bar.f90 | $(BUILD_DIRS)
	$(link) $@ $(MGEOBJ) $(OBJDIR)/triaxmassbin_f.o $(SRCDIR)/triaxmassbin_bar.f90

######################################################
#
# orblib_f, The orbit library program.
#
#######################################################

ORBLIBNMCDE= $(MGECDE) $(NUMERICSDIR)/numrec_arloc.f $(DOPCDE) $(SRCDIR)/orblib_f_new_mirror.f90
ORBLIBNMOBJ= $(MGEOBJ) $(OBJDIR)/numrec_arloc.o $(DOPOBJ) $(OBJDIR)/orblib_f_new_mirror.o

ifeq ($(FAST),TRUE)
  ORBLIBNMOBJ=$(ORBLIBNMCDE)
endif

$(OBJDIR)/orblib_f_new_mirror.o : $(SRCDIR)/orblib_f_new_mirror.f90 $(MGEOBJ) $(OBJDIR)/numrec_arloc.o $(DOPOBJ) | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/orblib_f_new_mirror.f90

orblib_new_mirror : $(BINDIR)/orblib_new_mirror

$(BINDIR)/orblib_new_mirror : $(ORBLIBNMOBJ) $(SRCDIR)/orblibprogram.f90 | $(BUILD_DIRS)
	$(link) $@  $(ORBLIBNMOBJ) $(SRCDIR)/orblibprogram.f90

orblib_bar : $(BINDIR)/orblib_bar

$(BINDIR)/orblib_bar : $(ORBLIBNMOBJ) $(SRCDIR)/orblibprogram_bar.f90 | $(BUILD_DIRS)
	$(link) $@  $(ORBLIBNMOBJ) $(SRCDIR)/orblibprogram_bar.f90

$(OBJDIR)/orbitstart_f.o : $(ORBLIBNMOBJ) $(MGEOBJ) $(SRCDIR)/orbitstart_f.f90 | $(BUILD_DIRS)
	$(fortran90) -o $@ $(SRCDIR)/orbitstart_f.f90

orbitstart : $(BINDIR)/orbitstart

$(BINDIR)/orbitstart : $(ORBLIBNMOBJ) $(OBJDIR)/orbitstart_f.o $(SRCDIR)/orbitstart.f90 | $(BUILD_DIRS)
	$(link) $@  $(ORBLIBNMOBJ) $(OBJDIR)/orbitstart_f.o $(SRCDIR)/orbitstart.f90

orbitstart_bar : $(BINDIR)/orbitstart_bar

$(BINDIR)/orbitstart_bar : $(ORBLIBNMOBJ) $(OBJDIR)/orbitstart_f.o $(SRCDIR)/orbitstart_bar.f90 | $(BUILD_DIRS)
	$(link) $@  $(ORBLIBNMOBJ) $(OBJDIR)/orbitstart_f.o $(SRCDIR)/orbitstart_bar.f90

##########################################
#
#  Utilities
#
##########################################

distclean:
	rm -rf $(BINDIR)
	rm -rf $(BUILDDIR)
	rm -f *.o *.il *.mod *.dyn work.* *.d *.exe ifc* *.dpi *.spi gmon.out orbitstart orbitstart_bar orblib_new_mirror orblib_bar triaxmass triaxmass_bar triaxmassbin triaxmassbin_bar

clean:
	rm -rf $(BUILDDIR)
	rm -f *.o *.il *.mod work.* *.d ifc*

profclean:
	rm -rf $(OBJDIR)
	rm -f *.o
