! Split from orblib_f_new_mirror.f90 without changing module names.

module integrator
    ! Integrator module. Integrates a point in the MGE potential
    use numeric_kinds
    implicit none
    private

    public  :: integrator_integrate

    public  :: integrator_set_current

    public  :: integrator_stop, integrator_find_orbtype

    public  :: integrator_setup_write, integrator_write

    private :: real_integrator

    ! current orbit
    integer(kind=i4b), public :: integrator_current

    ! contains the number of points generated by the integrator
    integer(kind=i4b), public :: integrator_points

    ! Starting point to begin with
    integer(kind=i4b), private :: integrator_start

    ! Number of different orbits
    integer(kind=i4b), private :: integrator_number

    ! Number of orbits to integrate for each orbit
    real(kind=dp), private :: integrator_n_orbits

    ! accuracy of integrator
    real(kind=dp), private :: integrator_accuracy

    ! Number of orbit ditherings
    integer(kind=i4b), public :: integrator_dithering

    ! is the current orbital set not regularizble?
    integer(kind=i4b), public :: totalnotregularizable

    ! temporary pos and velocity array for the dense output of the integrator
    real(kind=dp), private, allocatable, dimension(:, :) :: vel_t, pos_t

    ! functions and variables copied from original orblib
    private :: integrator_whichorbit, derivs, SOLOUT
    public :: integrator_setup_direct
    ! Inactive legacy file-reading setup routines are kept below as comments.
    ! The active Python path supplies begin arrays directly.

    ! information about the initial conditions for the orbit integration,
    ! and the grid in integral space.
    real(kind=dp), private, allocatable, dimension(:) :: xini, yini, zini
    real(kind=dp), private, allocatable, dimension(:) :: vxini, vzini
    real(kind=dp), public, allocatable, dimension(:) :: vyini, rcirc
    real(kind=dp), private, allocatable, dimension(:) :: vcirc, tcirc
    integer(kind=i4b), private, allocatable, dimension(:) :: regurizable

    integer(kind=i4b), private, allocatable, dimension(:) :: gEner, gI2, gI3

    integer(kind=i4b), public ::  nEner, nI2, nI3

    integer(kind=i4b), dimension(:), allocatable, private :: integrator_orbittypes
    real(kind=dp), private, allocatable, dimension(:, :)  ::  integrator_moments

    ! store the previously integrated orbit
    real(kind=dp), private, allocatable, dimension(:, :) :: pos_old, vel_old

contains

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_set_current(orbit)
        integer(kind=i4b), intent(in):: orbit
        !----------------------------------------------------------------------
        integrator_current = orbit
        Print *, "  * Starting at orbit", orbit + 1
        if (orbit < 0) stop " Can't start at that orbit"
        if (orbit > (nEner*nI2*nI3/integrator_dithering**3) - 1) &
            stop " Not so many orbits"

    end subroutine integrator_set_current

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ! INACTIVE LEGACY ROUTINE: Inactive legacy integrator setup: active Python path supplies begin arrays to integrator_setup_direct.
    ! Retained as comments for reference; do not call from active direct ABI path.
!     subroutine integrator_setup()
!         use initial_parameters, only: iniparam, orbit_dithering
!         !use triaxpotent, only : tp_setup
!         use interpolpot, only: ip_setup
!         !----------------------------------------------------------------------
!         integer(kind=i4b) :: ndith3
!         print *, "  ** Setting up integrator module"
!         print *, "  * Calling MGE setup"
!         call iniparam()
!         print *, "  * Calling ip_setup"
!         call ip_setup()
!         call ini_integ()
!         print *, "  * How many orbits should be integrated?"
!         read *, integrator_n_orbits
!         print *, "    ", integrator_n_orbits
!         if (integrator_n_orbits < 1) stop " Too few orbits"
!         print *, "  * How many points should be generated per starting point?"
!         read *, integrator_points
!         print *, "    ", integrator_points
!         integrator_dithering = orbit_dithering
!         ndith3 = integrator_dithering**3
!         allocate (integrator_orbittypes(ndith3))
!         allocate (integrator_moments(5, ndith3))
!         if (integrator_points < 1) stop " Too few points"
!         print *, "  * At which starting point should be started?"
!         read *, integrator_start
!         print *, "    ", integrator_start
!         call integrator_set_current(integrator_start - 1)
!         print *, "  * How many starting points should be integrated?"
!         read *, integrator_number
!         print *, "    ", integrator_number
!         if (integrator_number == -1) integrator_number = &
!             (nEner*nI2*nI3/integrator_dithering**3)
! 
!         if (integrator_number < 1) stop " To few starting points"
!         if (integrator_number > &
!             (nEner*nI2*nI3/integrator_dithering**3)) &
!             & stop " Too many orbits in total"
!         print *, "  * How great should te accuracy be of the integrator?"
!         read *, integrator_accuracy
!         print *, "    ", integrator_accuracy
!         if (integrator_accuracy < 0 .or. 0.5 < integrator_accuracy) &
!           & stop " wrong accuracy"
! 
!         print *, "  ** integrator module setup finished"
! 
!     end subroutine integrator_setup

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ! INACTIVE LEGACY ROUTINE: Inactive legacy bar integrator setup: active direct shared-library path is non-bar triaxial.
    ! Retained as comments for reference; do not call from active direct ABI path.
!     subroutine integrator_setup_bar()
!         use initial_parameters, only: iniparam_bar, orbit_dithering
!         !use triaxpotent, only : tp_setup
!         use interpolpot, only: ip_setup_bar
!         !----------------------------------------------------------------------
!         integer(kind=i4b) :: ndith3
!         print *, "  ** Setting up integrator module"
!         print *, "  * Calling MGE setup"
!         call iniparam_bar()
!         print *, "  * Calling ip_setup_bar"
!         call ip_setup_bar()
!         call ini_integ()
!         print *, "  * How many orbits should be integrated?"
!         read *, integrator_n_orbits
!         print *, "    ", integrator_n_orbits
!         if (integrator_n_orbits < 1) stop " Too few orbits"
!         print *, "  * How many points should be generated per starting point?"
!         read *, integrator_points
!         print *, "    ", integrator_points
!         integrator_dithering = orbit_dithering
!         ndith3 = integrator_dithering**3
!         allocate (integrator_orbittypes(ndith3))
!         allocate (integrator_moments(5, ndith3))
!         if (integrator_points < 1) stop " Too few points"
!         print *, "  * At which starting point should be started?"
!         read *, integrator_start
!         print *, "    ", integrator_start
!         call integrator_set_current(integrator_start - 1)
!         print *, "  * How many starting points should be integrated?"
!         read *, integrator_number
!         print *, "    ", integrator_number
!         if (integrator_number == -1) integrator_number = &
!             (nEner*nI2*nI3/integrator_dithering**3)
! 
!         if (integrator_number < 1) stop " To few starting points"
!         if (integrator_number > &
!             (nEner*nI2*nI3/integrator_dithering**3)) &
!             & stop " Too many orbits in total"
!         print *, "  * How great should te accuracy be of the integrator?"
!         read *, integrator_accuracy
!         print *, "    ", integrator_accuracy
!         if (integrator_accuracy < 0 .or. 0.5 < integrator_accuracy) &
!           & stop " wrong accuracy"
! 
!         print *, "  ** integrator module setup finished"
! 
!     end subroutine integrator_setup_bar

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_setup_direct(begin_values, begin_noreg, begin_rows, &
                                       n_orbits_input, points_input, &
                                       start_input, number_input, &
                                       accuracy_input)
        use initial_parameters, only: orbit_dithering, param_nEner => nEner, &
                                      param_nI2 => nI2, param_nI3 => nI3
        integer(kind=i4b), intent(in) :: begin_rows
        real(kind=dp), intent(in), dimension(begin_rows, 9) :: begin_values
        integer(kind=i4b), intent(in), dimension(begin_rows) :: begin_noreg
        real(kind=dp), intent(in) :: n_orbits_input
        integer(kind=i4b), intent(in) :: points_input
        integer(kind=i4b), intent(in) :: start_input, number_input
        real(kind=dp), intent(in) :: accuracy_input
        integer(kind=i4b) :: i, ndith3
        real(kind=dp), dimension(9) :: begin_record
        character(len=270) :: legacy_begin_line

        print *, "  ** Setting up integrator module from direct Python input"

        if (allocated(xini)) then
            deallocate (xini, yini, zini, vxini, vyini, vzini, gener, gi2, gi3, &
                        vcirc, tcirc, rcirc, regurizable)
        end if
        if (allocated(integrator_orbittypes)) deallocate(integrator_orbittypes)
        if (allocated(integrator_moments)) deallocate(integrator_moments)

        nEner = param_nEner
        nI2 = param_nI2
        nI3 = param_nI3
        if (begin_rows /= nEner*nI2*nI3) stop "direct begin array has wrong row count"

        allocate (xini(begin_rows), yini(begin_rows), zini(begin_rows), &
                  vxini(begin_rows), vyini(begin_rows), vzini(begin_rows), &
                  rcirc(begin_rows), tcirc(begin_rows), vcirc(begin_rows), &
                  gEner(begin_rows), gI2(begin_rows), gI3(begin_rows), &
                  regurizable(begin_rows))

        do i = 1, begin_rows
            gI3(i) = modulo((i - 1), nI3) + 1
            gI2(i) = modulo(((i - 1)/nI3), nI2) + 1
            gEner(i) = ((i - 1)/(nI3*nI2)) + 1
            begin_record(:) = begin_values(i, :)
            write (legacy_begin_line, fmt="(9ES30.10)") begin_record(:)
            read (legacy_begin_line, fmt="(9ES30.10)") begin_record(:)
            xini(i) = begin_record(1)
            yini(i) = begin_record(2)
            zini(i) = begin_record(3)
            vxini(i) = begin_record(4)
            vyini(i) = begin_record(5)
            vzini(i) = begin_record(6)
            rcirc(i) = begin_record(7)
            tcirc(i) = begin_record(8)
            vcirc(i) = begin_record(9)
            regurizable(i) = begin_noreg(i)
        end do

        integrator_n_orbits = n_orbits_input
        if (integrator_n_orbits < 1) stop " Too few orbits"
        integrator_points = points_input
        if (integrator_points < 1) stop " Too few points"
        integrator_dithering = orbit_dithering
        ndith3 = integrator_dithering**3
        allocate (integrator_orbittypes(ndith3))
        allocate (integrator_moments(5, ndith3))
        integrator_start = start_input
        call integrator_set_current(integrator_start - 1)
        integrator_number = number_input
        if (integrator_number == -1) integrator_number = &
            (nEner*nI2*nI3/integrator_dithering**3)
        if (integrator_number < 1) stop " To few starting points"
        if (integrator_number > &
            (nEner*nI2*nI3/integrator_dithering**3)) &
            & stop " Too many orbits in total"
        integrator_accuracy = accuracy_input
        if (integrator_accuracy < 0 .or. 0.5 < integrator_accuracy) &
          & stop " wrong accuracy"

        print *, "  ** direct integrator module setup finished"
    end subroutine integrator_setup_direct

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_stop()
        !----------------------------------------------------------------------
        if (allocated(xini)) then
            deallocate (xini, yini, zini, vxini, vyini, vzini, gener, gi2, gi3, &
                        vcirc, tcirc, rcirc, regurizable, vel_old, pos_old)
        end if

        if (allocated(pos_old)) then
            deallocate (pos_old, vel_old)
            deallocate (pos_t, vel_t)
        end if

        close (unit=30)
    end subroutine integrator_stop

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_integrate(pos, vel, otype, done, first, alldone)
      use initial_parameters    , only : conversion_factor , Omega     ! (BT)
        logical, intent(out):: done, alldone
        logical, intent(in):: first
        real(kind=dp), intent(out), dimension(integrator_points, 3) :: pos
        real(kind=dp), intent(out), dimension(integrator_points, 3) :: vel
        integer(kind=i4b), intent(out) :: otype
        integer(kind=i4b), save :: dith = 0
        integer(kind=i4b)    :: temporbit
        real    (kind=dp ), dimension(6) :: YY ! (BT)
        real    (kind=dp )   :: Enjo,r_mean,lz2,vca,Svr,Svt,Svz ! (BT)
        real(kind=dp), dimension(5) :: moments
        real    (kind=dp ),dimension(3) :: moments2 ! (BT)
        !----------------------------------------------------------------------
        alldone = .false.
        if (first) then
            integrator_current = integrator_current + 1
            dith = 0
            totalnotregularizable = 0
            print *, "  * Starting integrating :", integrator_current
        end if
        dith = dith + 1
        if (dith <= integrator_dithering**3 .and. &
            integrator_current <= integrator_number) then

            call integrator_whichorbit(integrator_current, dith, temporbit)

            ! check if there is an unregurizable compenent in this set
            if (regurizable(temporbit) == 1) totalnotregularizable = 1
            !print*,"  * Starting integrating :",integrator_current,dith,temporbit
            call real_integrator(temporbit, pos, vel)
            call integrator_find_orbtype(otype, moments, pos, vel) ! (BT)
            integrator_orbittypes(dith) = otype
            integrator_moments(:, dith) = moments
            done = .false.

            ! write orbit information  in case of figure rotation (BT)
            if (Omega /= 0.0_dp ) then
               call integrator_find_rotating_moments(moments2, pos, vel)
               r_mean = moments(4)*conversion_factor**(-1.0_dp)
               lz2    = moments(3)*conversion_factor**(-1.0_dp)
               !cir = moments(3)/( SQRT(moments(5))*moments(4) )
               vca  = moments(5)
               Svr  = moments2(1)
               Svt  = moments2(2)
               Svz  = moments2(3)

               YY(1) =  pos(1,1)
               YY(2) =  pos(1,2)
               YY(3) =  pos(1,3)
               YY(4) =  vel(1,1)
               YY(5) =  vel(1,2)
               YY(6) =  vel(1,3)

               ! Compute and store start energy at begin point
               call computer_energy(YY,Enjo)

               write (unit=32, fmt="(25es13.5)")  Enjo, r_mean, lz2, vca, Svr, Svt, Svz
            endif
            ! end write orbit information

        else
            ! integrating done. Set 'done' to true and return.
            pos(:, :) = 0.0_dp
            vel(:, :) = 0.0_dp
            done = .true.
        end if

        if (integrator_current > integrator_number) alldone = .true.

    end subroutine integrator_integrate

!  !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
!  subroutine integrator_integrate_nodith(pos,vel,otype,done,first,alldone)
!    logical           ,intent(out):: done,alldone
!    logical           ,intent(in):: first
!    real    (kind=dp ),intent(out),dimension(integrator_points,3) :: pos
!    real    (kind=dp ),intent(out),dimension(integrator_points,3) :: vel
!    integer (kind=i4b),intent(out) :: otype
!    integer (kind=i4b),save :: dith=0
!    integer (kind=i4b)    :: temporbit
!  !----------------------------------------------------------------------
!    if (first) then
!       integrator_current=integrator_current+1
!       dith=(integrator_dithering**3)/2+1
!       totalnotregularizable=0
!       print*,"  * Starting integrating :",integrator_current
!    endif
!    if (first .and. &
!         integrator_current <= integrator_number) then
!
!       call integrator_whichorbit(integrator_current,dith,temporbit)
!
!       ! check if there is an unregurizable compenent in this set
!       if (regurizable(temporbit) == 1) totalnotregularizable=1
!       print*,"  * Starting integrating :",integrator_current,dith,temporbit
!       call real_integrator (temporbit,pos,vel)
!       call integrator_find_orbtype(otype,pos,vel)
!       integrator_orbittypes(dith)=otype
!       done=.false.
!    else
!       ! integrating done. Set 'done' to true and return.
!       pos(:,:)=0.0_dp
!       vel(:,:)=0.0_dp
!       done=.true.
!    end if
!
!    if (integrator_current > integrator_number) alldone=.true.
!
!  end subroutine integrator_integrate_nodith

! This routines finds the orbit dither number
    subroutine integrator_whichorbit(orbit, dith, dithorbit)
        integer(kind=i4b), intent(in)      :: orbit, dith
        integer(kind=i4b), intent(out)     :: dithorbit
        integer(kind=i4b) :: E1, I2, I3, nd
        integer(kind=i4b) :: d1, d2, d3, DO1, DO2, DO3

        nd = integrator_dithering
        ! Reconstruct E, I2 and I3 number from orbit number:
        I3 = modulo((orbit - 1), nI3/nd) + 1
        I2 = modulo(((orbit - 1)/(nI3/nd)), nI2/nd) + 1
        E1 = ((orbit - 1)/(nI3*nI2/(nd*nd))) + 1
        ! Find which orbit dither we are currently at:
        d3 = modulo((dith - 1), nd) + 1
        d2 = modulo(((dith - 1)/nd), nd) + 1
        d1 = ((dith - 1)/(nd*nd)) + 1
        ! combine previous results to find the undithered orbit number
        DO3 = (I3 - 1)*nd + d3
        DO2 = (I2 - 1)*nd + d2
        DO1 = (E1 - 1)*nd + d1
        dithorbit = DO3 + ((DO2 - 1)*nI3) + ((do1 - 1)*nI3*nI2)
    end subroutine integrator_whichorbit

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine real_integrator(orbit, pos, vel)
        integer(kind=i4b), intent(in)                                :: orbit
        real(kind=dp), intent(out), dimension(integrator_points, 3) :: pos
        real(kind=dp), intent(out), dimension(integrator_points, 3) :: vel
        !----------------------------------------------------------------------
        integer(kind=i4b) :: IOUT, IDID, ITOL
        integer(kind=i4b), parameter :: N = 6, NRDENS = 6, LWORK = 11*N + 8*NRDENS + 21
        integer(kind=i4b), parameter :: LIWORK = NRDENS + 21
        real(kind=dp) :: X, Xend, RTOL, ATOL
        real(kind=dp), dimension(6) :: Y
        real(kind=dp), dimension(lwork) :: WORK
        integer(kind=i4b), dimension(liwork) :: IWORK
        real(kind=dp), dimension(2) :: RPAR
        integer(kind=i4b), dimension(1) :: IPAR
        real(kind=dp), save :: stepsize = 0.0_dp
        real(kind=dp) :: Ebeg, Eend
        integer(kind=i4b), save :: stored_orbit = 0

        if (.NOT. allocated(pos_old)) then
            ! setting up the array for storing the points.
            allocate (pos_old(integrator_points, 3), vel_old(integrator_points, 3))
            allocate (pos_t(integrator_points, 3), vel_t(integrator_points, 3))

        else
            if (integrator_points /= size(pos_old, 1)) then
                deallocate (pos_old, vel_old, pos_t, vel_t)
                allocate (pos_old(integrator_points, 3), vel_old(integrator_points, 3))
                allocate (pos_t(integrator_points, 3), vel_t(integrator_points, 3))
                ! Reset the flag to indicate that we do not have an orbit stored.
                stored_orbit = 0
            end if
        end if

        ! --- REQUIRED TOLERANCE
        ! The integrator keeps the local error on Y(I)
        ! below RTOL(I)*ABS(Y(I)) + ATOL(I).
        ITOL = 0 ! Tolerances are scalars
        RTOL = integrator_accuracy
        ATOL = integrator_accuracy!/10000.0_dp
        ! The Absolutie Tolerance used to be set-up as a vector
        ! ATOL= 1e-6* (/ rcirc(orbit), rcirc(orbit), rcirc(orbit), &
        !                   vcirc(orbit), vcirc(orbit), vcirc(orbit) /)

        Y(1) = xini(orbit)  !  x(0)
        Y(2) = yini(orbit)  !  y(0)
        Y(3) = zini(orbit)  !  z(0)
        Y(4) = vxini(orbit)  ! vx(0)
        Y(5) = vyini(orbit)  ! vy(0)
        Y(6) = vzini(orbit)  ! vz(0)

        ! Compute and store start energy at begin point
        call computer_energy(Y, Ebeg)

        DO  ! While integrating has not succeeded
            ! setting up the array for storing the points.
            ! --- DIMENSION OF THE SYSTEM
            IDID = 0
            ! --- OUTPUT ROUTINE (AND DENSE OUTPUT) IS USED DURING INTEGRATION
            IOUT = 2
            ! --- INITIAL VALUES
            X = 0.0

            Y(1) = xini(orbit)  !  x(0)
            Y(2) = yini(orbit)  !  y(0)
            Y(3) = zini(orbit)  !  z(0)
            Y(4) = vxini(orbit)  ! vx(0)
            Y(5) = vyini(orbit)  ! vy(0)
            Y(6) = vzini(orbit)  ! vz(0)

            ! --- ENDPOINT OF INTEGRATION
            XEND = integrator_n_orbits*tcirc(orbit)
            ! Stepsize. Make sure enough steps are in the integration by adding
            ! room for a couple of  extra steps. RvdB 19/12/04
            RPAR(2) = XEND/(integrator_points + 4)
            RPAR(1) = 0.0 ! Unused

            ! --- VALUES FOR PARAMETERS
            ! Default values are used when IWORK or WORK are zero
            IWORK(:) = 0
            WORK(:) = 0.0_dp
            ! Maximum of allowed steps (just really high) (100000)
            IWORK(1) = max(floor(min(dble(huge(1_i4b) - 1), 1.0_dp/RTOL*integrator_n_orbits/200), kind=i4b), 100000_i4b)
            !number of dense components needed. (all in our case)
            IWORK(5) = NRDENS
            !stiffness detection (negative --> do not try to detect)
            IWORK(4) = -1
            !give guess of stepsize
            WORK(7) = stepsize

            !CALL OF THE SUBROUTINE DOPRI8 ( The dop853 integrator.)
            CALL DOP853(N, derivs, X, Y, XEND, RTOL, ATOL, ITOL, SOLOUT, IOUT, &
                        WORK, LWORK, IWORK, LIWORK, RPAR, IPAR, IDID)

!   IPAR(1)    COUNT   NUMBER OF STORED INTEGRATION STEPS IN pos_t AND vel_t
!   IWORK(17)  NFCN    NUMBER OF FUNCTION EVALUATIONS
!   IWORK(18)  NSTEP   NUMBER OF COMPUTED STEPS
!   IWORK(19)  NACCPT  NUMBER OF ACCEPTED STEPS
!   IWORK(20)  NREJCT  NUMBER OF REJECTED STEPS (DUE TO ERROR TEST),
!                      (STEP REJECTIONS IN THE FIRST STEP ARE NOT COUNTED)
!   print*,"  * Integrator output"
!   print*,iwork(17:20)

            ! compute final energy
            call computer_energy(Y, Eend)

            select case (IDID)
            case (-1)
                stop "integrator:  INPUT IS NOT CONSISTENT,"
            case (-2)
                print *, "integrator:  LARGER NMAX IS NEEDED,"
            case (-3)
                print *, "integrator:  STEP SIZE BECOMES TOO SMALL."
            case (-4)
                stop "integrator:  PROBLEM IS PROBABLY STIFF (INTERRUPTED)."
            case default
                ! Integrating went ok!

                if (abs((Ebeg - Eend)/Ebeg) .lt. 0.01) then
                    ! If Integration conserved energy within 1 percent then do
                    !   - Store pos and vel as failsafe for next orbit integration
                    !   - Swap the points to the correct array.
                    pos(:, :) = pos_t(:, :)
                    pos_old(:, :) = pos_t(:, :)
                    vel_old(:, :) = vel_t(:, :)
                    vel(:, :) = vel_t(:, :)
                    stored_orbit = 1
                    stepsize = work(7)  ! Store integrater stepsize for next itegration
                    EXIT  ! integration was succesfull
                end if
                print *, "Energy conserved to ", (Ebeg - Eend)/Ebeg*100.0_dp, ", Increasing integrator accuracy"
            end select

            if (RTOL .lt. 1e-12_dp) then
                print *, '  * orbit ', orbit, ' failed. Energy conserved up to ', (Ebeg - Eend)/Ebeg*100.0_dp
                ! Orbit integration unsuccesfull even at higher accuracy
                if (stored_orbit .eq. 0) stop 'Abort, No backup orbit stored'
                pos_t(:, :) = pos_old(:, :)
                vel_t(:, :) = vel_old(:, :)
                EXIT ! Integration not succesfull
            end if

            ! Increase accuracy and try again.
            RTOL = RTOL*0.1_dp
            ATOL = ATOL*0.1_dp

            print *, '  * Retrying orbit', orbit
        end do

    end subroutine real_integrator

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_setup_write(handle)
        integer(kind=i4b), intent(in) :: handle
        integer(kind=i4b)            :: t1, t2, t3, t4
        !----------------------------------------------------------------------
        print *, "  * Writing integrator output header"
        t1 = (nEner*nI2*nI3/integrator_dithering**3)
        t2 = nEner/integrator_dithering
        t3 = nI2/integrator_dithering
        t4 = nI3/integrator_dithering
        write (unit=handle) t1, t2, t3, t4, integrator_dithering

        write (unit=30, fmt=*) Nener*ni2*ni3, integrator_dithering**3

    end subroutine integrator_setup_write

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_write(hdl)
        integer(kind=i4b), intent(in) :: hdl
        !----------------------------------------------------------------------
        integer(kind=i4b)            :: nd, orbit, I3, I2, E1
        orbit = integrator_current

        nd = integrator_dithering
        ! Reconstruct E, I2 and I3 number from orbit number:
        I3 = modulo((orbit - 1), nI3/nd) + 1
        I2 = modulo(((orbit - 1)/(nI3/nd)), nI2/nd) + 1
        E1 = ((orbit - 1)/(nI3*nI2/(nd*nd))) + 1

        ! write information about the orbit
        write (unit=hdl) orbit, E1, I2, I3, totalnotregularizable
        write (unit=hdl) integrator_orbittypes(:)

        write (unit=30, fmt="(25es13.5)") integrator_moments(:, :)
    end subroutine integrator_write

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    ! INACTIVE LEGACY ROUTINE: Inactive legacy begin-file reader: active Python path passes begin arrays in memory.
    ! Retained as comments for reference; do not call from active direct ABI path.
!     subroutine ini_integ()
!         !----------------------------------------------------------------------
!         character(len=30) :: infil
!         integer(kind=i4b) :: i
! 
!         print *, "  * Give name of file with begin conditions"
!         read (unit=*, fmt="(a30)") infil
!         print *, "   ", infil
!         open (unit=31, file=infil, status="OLD", action="read", position="rewind")
! 
!         read (unit=31, fmt=*) nEner, nI2, nI3
! 
!         i = nEner*nI2*nI3
! 
!         print *, " * Orbits in the input file"
!         print *, nEner, nI2, nI3, i
! 
!         IF (.NOT. ALLOCATED(xini)) &
!             allocate (xini(i), yini(i), zini(i), vxini(i), vyini(i), vzini(i), rcirc(i), &
!                       tcirc(i), vcirc(i), gEner(i), gI2(i), gI3(i), regurizable(i))
! 
!         read (unit=31, fmt="(3I5,9ES30.10,I4)") (gener(i), gi2(i), gi3(i), xini(i), &
!                                                  yini(i), zini(i), vxini(i), vyini(i), &
!                                                  vzini(i), rcirc(i), tcirc(i), &
!                                                  vcirc(i), regurizable(i), &
!                                                  i=1, nEner*nI2*nI3)
! 
!         close (unit=31)
! 
!     end subroutine ini_integ

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine derivs(N, xin, yin, dydx, RPAR, IPAR)
      use initial_parameters, only: Omega        ! (BT)
        use interpolpot, only: ip_accel
        !use triaxpotent, only : tp_accel
        integer, intent(in)              :: N
        real(kind=dp), intent(in)              :: xin
        real(kind=dp), intent(in), dimension(6) :: yin
        real(kind=dp), intent(out), dimension(6) :: dydx
        real(kind=dp), intent(inout), dimension(2) :: RPAR
        integer(kind=i4b), intent(inout), dimension(1) :: IPAR
        !----------------------------------------------------------------------

        ! subroutine which returns the right-hand side derivatives.
        !   x      = t
        !   yin(1) = x
        !   yin(2) = y
        !   yin(3) = z
        !   yin(4) = dx/dt
        !   yin(5) = dy/dt
        !   yin(6) = dz/dt

        if (Omega == 0.0_dp ) then
           ! First calculate the true accelerations at the given position
           dydx(1:3) = yin(4:6)
           call ip_accel(yin(1), yin(2), yin(3), dydx(4), dydx(5), dydx(6))
        else
           ! Rotating frame with Omega pattern speed (BT)
           dydx(1) =  yin(4) + Omega*yin(2)  ! extra terms for integration in co-rotating frame
           dydx(2) =  yin(5) - Omega*yin(1)
           dydx(3) =  yin(6)

           call ip_accel(yin(1),yin(2),yin(3),dydx(4),dydx(5),dydx(6))

           dydx(4) =  dydx(4) + Omega*yin(5)
           dydx(5) =  dydx(5) - Omega*yin(4)
           dydx(6) =  dydx(6)
        end if

    end subroutine derivs

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    SUBROUTINE SOLOUT(NR, XOLD, X, Y, N, CON, ICOMP, ND, RPAR, IPAR, IRTRN)
        ! --- PRINTS SOLUTION AT EQUIDISTANT OUTPUT-POINTS
        ! --- BY USING "CONTD8", THE CONTINUOUS COLLOCATION SOLUTION
        integer, intent(in)    :: NR, N, ND
        real(kind=dp), intent(in)    :: XOLD, X
        integer, intent(inout) :: IRTRN
        real(kind=dp), intent(in), dimension(N)    :: Y
        real(kind=dp), intent(in), dimension(8*ND) :: CON
        integer(kind=i4b), intent(in), dimension(ND)   :: ICOMP
        real(kind=dp), intent(inout), dimension(2)    :: RPAR
        integer(kind=i4b), intent(inout), dimension(1)    :: IPAR
        !----------------------------------------------------------------------
        real(kind=dp), save          :: XOUT
        integer(kind=i4b), save          :: count = 0
        real(kind=dp)               :: contd8, step, rnd
        real(kind=dp)               :: ran1
        step = RPAR(2)
        IF (NR == 1) THEN
            ! Start storing the orbit after 1+? steps to avoid aliasing
            rnd = ran1(1)
            ! call random_number(rnd) ! 0 < rnd < 1
            XOUT = X + step*(1.0_dp + rnd)
            count = 0
            IPAR(1) = 0
        ELSE
            do
                ! Make sure count > integrator_points to make sure we do not
                ! go out of bounds on pos_t(:,:). RvdB, DK 16/06/03
                IF (X < XOUT .or. count >= integrator_points) exit
                count = count + 1
                IPAR(1) = count
                pos_t(count, 1) = CONTD8(1, XOUT, CON, ICOMP, ND)
                pos_t(count, 2) = CONTD8(2, XOUT, CON, ICOMP, ND)
                pos_t(count, 3) = CONTD8(3, XOUT, CON, ICOMP, ND)
                vel_t(count, 1) = CONTD8(4, XOUT, CON, ICOMP, ND)
                vel_t(count, 2) = CONTD8(5, XOUT, CON, ICOMP, ND)
                vel_t(count, 3) = CONTD8(6, XOUT, CON, ICOMP, ND)
                XOUT = XOUT + step
            end do
        END IF
    END SUBROUTINE SOLOUT

    !++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
    subroutine integrator_find_orbtype(type, moments, pos, vel) ! (BT)
        integer(kind=i4b), intent(out) :: type
        real(kind=dp), intent(out), dimension(:) :: moments ! (BT)
        real(kind=dp), intent(in), dimension(:, :) :: pos
        real(kind=dp), intent(in), dimension(size(pos, 1), 3) :: vel
        !----------------------------------------------------------------------
        real(kind=dp) :: lxc, lyc, lzc
        real(kind=dp), dimension(size(pos, 1)) :: t
        real(kind=dp), parameter :: nul = 0.0_dp
        !  Lx = y*Vz-z*Vy
        t = pos(:, 2)*vel(:, 3) - pos(:, 3)*vel(:, 2)
        lxc = maxval(t)*minval(t)
        moments(1) = sum(t)/size(pos, 1)

        !  Ly = z*Vx-x*Vz
        t = pos(:, 3)*vel(:, 1) - pos(:, 1)*vel(:, 3)
        lyc = maxval(t)*minval(t)
        moments(2) = sum(t)/size(pos, 1)

        !  Lz = x*Vy-y*Vx
        t = pos(:, 1)*vel(:, 2) - pos(:, 2)*vel(:, 1)
        lzc = maxval(t)*minval(t)
        moments(3) = sum(t)/size(pos, 1)

        ! assume orbit is chaotic, unless proven otherwise.
        type = 5

        ! X tube
        if (lxc > nul .and. lyc < nul .and. lzc < nul) type = 1
        ! Y tube
        if (lxc < nul .and. lyc > nul .and. lzc < nul) type = 2
        ! Z tube
        if (lxc < nul .and. lyc < nul .and. lzc > nul) type = 3
        ! Box
        if (lxc < nul .and. lyc < nul .and. lzc < nul) type = 4

        ! vector lenghts should be equal, otherwise DIM  is wrong
        !print*,size(sum(pos(:,:)**2,dim=2)) ,  size(pos,1)

        ! mean radius
        moments(4) = sum(sqrt(sum(pos(:, :)**2, dim=2)))/size(pos, 1)

        ! second moment = vxx+vyy+vzz + 2vxy + 2vyz +2vzx
        moments(5) = sum(sum(vel(:, :)**2, dim=2) &
                         + 2*(vel(:, 1)*vel(:, 2) &
                              + vel(:, 2)*vel(:, 3) &
                              + vel(:, 3)*vel(:, 1)))/size(pos, 1)

        !print*,moments(3),moments(5),moments(3)/moments(4)/sqrt(moments(5))

    end subroutine integrator_find_orbtype

    subroutine integrator_find_rotating_moments(moments2, pos, vel) ! (BT)
        real(kind=dp), intent(out), dimension(:) :: moments2 ! (BT)
        real(kind=dp), intent(in), dimension(:, :) :: pos
        real(kind=dp), intent(in), dimension(size(pos, 1), 3) :: vel
        real(kind=dp), dimension(size(pos, 1)) :: vr, vt, vz ! (BT)
        real(kind=dp) :: sd_vr, sd_vt, sd_vz, mean_vr, mean_vt, mean_vz, n ! (BT)
        !----------------------------------------------------------------------
        ! convert velocity to cylinderical  (anisotropy) (BT)
        vr = ( pos(:,1) * vel(:,1) +  pos(:,2) * vel(:,2) ) / sqrt(pos(:,1)**2+pos(:,2)**2)
        vt = ( pos(:,1) * vel(:,2) +  pos(:,2) * vel(:,1) ) / sqrt(pos(:,1)**2+pos(:,2)**2)
        vz = vel(:,3)

        N = size(pos,1)
        mean_vr = sum(vr) / N
        sd_vr = sqrt(sum((vr-mean_vr)**2) / N)

        mean_vt = sum(vt) / N
        sd_vt = sqrt(sum((vt-mean_vt)**2) / N)

        mean_vz = sum(vz) / N
        sd_vz = sqrt(sum((vz-mean_vz)**2) / N)

        moments2(1) =  sd_vr
        moments2(2) =  sd_vt
        moments2(3) =  sd_vz

    end subroutine integrator_find_rotating_moments

    subroutine computer_energy(Y, E)
      use initial_parameters, only: Omega ! (BT)
        ! Compute the energy of a particle.
        use interpolpot, only: ip_potent
        real(kind=dp), intent(in), dimension(6) :: Y
        real(kind=dp), intent(out) :: E
        real(kind=dp) :: ep
        call ip_potent(y(1), y(2), y(3), Ep)
        if (Omega /= 0.0_dp ) then
           ep = ep + Omega*(y(1)*y(5)-y(2)*y(4)) ! check the conservation of effective potential (BT)
        end if
        E = ep - 0.5_dp*(y(4)**2 + y(5)**2 + y(6)**2)
    end subroutine computer_energy

end module integrator
